---
title: "Education"
---

## **Ph.D., Public Administration - 2026 (expected)**

#### University of Illinois Chicago (UIC)

##### Department of Public Policy, Management, and Analytics

Concentration: Urban Governance and Networks

Dissertation: “*Exploring the Dynamics of Interlocal Agreements Diffusion: Measurement, Geographic Proximity, and Network Influences*.”

Committee: Jered B. Carr (chair), University of Illinois Chicago; Michael Siciliano, University of Illinois Chicago; Kelly LeRoux, University of Illinois Chicago; Meghan Rubado, Cleveland State University; Hongtao Yi, Florida State University.

## **Ph.D., Public Policy - 2022**

#### Center for Research and Teaching in Economics (CIDE)

##### Public Administration Division

Dissertation: “*Discourse Networks, Advocacy Coalitions, and Policy Decisions: The Power Generation Policy in Mexico, 1994-2018*.”

Committee: Edgar Ramírez de la Cruz (chair), CIDE, Juan Rosellón (chair), CIDE, Ramiro Berardo, Ohio State University.

## **M.A., Politics and Public Management - 2016**

#### Iberoamericana University - León (UIA)

## **B.A., Business Administration - 2010**

#### Iberoamericana University - León (UIA)
