---
title: ""
---

## About me

My name is Raul Gutierrez Meave. I am a Ph.D. student of Public Administration at the Policy, Management and Analytics Department at the University of Illinois Chicago (UIC). With a previous Ph.D. in Public Policy at the Center for Research and Teaching in Economics (CIDE), my research focuses broadly on urban governance, networks, and local policymaking. More specifically, I am interested in studying how local governments adopt policy innovations. In particular, I aim to examine how intergovernmental agreements for service delivery spread to other municipalities through interlocal collaborations and networks over time and space. I am also interested in studying the impacts of urban infrastructure on various policy domains and dynamics within cities. My goal goal is to uncover insights into building more resilient, sustainable, and livable communities.

## Education

#### **Ph.D., Public Administration - 2026 (expected)**

University of Illinois Chicago (UIC)

Department of Public Policy, Management, and Analytics

Concentration: Urban Governance and Networks

Dissertation: *“Innovation, Competitive pressures, and Networked Gains: Understanding the Diffusion Dynamics of Intergovernmental Contractual Agreements.”*

#### **Ph.D., Public Policy - 2022**

Center for Research and Teaching in Economics (CIDE)

Public Administration Division

Dissertation: “*Discourse Networks, Advocacy Coalitions, and Policy Decisions: The Power Generation Policy in Mexico, 1994-2018*.”

Committee: Edgar Ramírez de la Cruz, CIDE, Juan Rosellón, CIDE, Ramiro Berardo, Ohio State University. 

#### **M.A., Politics and Public Management - 2016**

Iberoamericana University (UIA)

#### **B.A., Business Administration - 2010**

Iberoamericana University (UIA)
