---
title: "Research"
---

#### Refereed Journal Articles

6.  Siciliano, M., E-Zhera, M., Gutiérrez-Meave, R., Deslatte, A., Krause, R. (2026). ["Local Governance and Green Ties: Assessing the Relationship Between Functional and Institutional Collective Action."](https://journals.sagepub.com/doi/10.1177/0160323X251410491) *State and Local Government Review*.

<!-- -->

5.  Gutiérrez-Meave, R., Zhang, S., Carr, J., Siciliano, M. (2025). [“Integrating Formal and Relational Contracting: The Link Between Network Structure and Contract Design in Interlocal Collaboration Agreements.”](https://onlinelibrary.wiley.com/doi/10.1111/padm.13050) *Public Administration*.

<!-- -->

4.  Gutiérrez-Meave, R. (2024). [“Advocacy Coalitions, Soft Power, and Policy Change in Mexican Electricity Policy: A Discourse Network Analysis.”](https://bristoluniversitypressdigital.com/view/journals/pp/aop/article-10.1332-03055736Y2023D000000005/article-10.1332-03055736Y2023D000000005.xml) *Policy and Politics*.

<!-- -->

3.  Gutiérrez-Meave, R., Rosellón, J., Sarmiento, L. (2024). [“Policy Reversals in Transitional Markets: The Effect of Changing Marginal-cost to Physical-order Dispatch in the Mexican Power Sector.”](https://www.iaee.org/eeep/article/504) *Economics of Energy & Environmental Policy*.

<!-- -->

2.  Massa, R., Fondevila, G., Gutiérrez-Meave, R., Bonilla, G. (2023). [“Clandestine Dumpsites and Crime in Mexico City: Revisiting the Broken Windows Theory.”](https://journals.sagepub.com/doi/full/10.1177/00111287231186083?casa_token=fCXTlpNqf0sAAAAA%3AchhFRuG0I_QfNgmesnMbQ7JQ7cAX-1XTgXe8NNgPM_rqWNSFMzTIkuNFYaD7KGW14K4mOPPGPb8N) *Crime & Delinquency*.

<!-- -->

1.  Bonilla, G., Gutiérrez-Meave, R. (2022). [“Zoning Out Robbery? An Empirical Study in Mexico City.”](https://www.tandfonline.com/doi/abs/10.1080/10511482.2021.1915357) *Housing Policy Debate*.

#### Book Chapters

2.  Rosellón, J., Núñez, H., Gutiérrez-Meave, R. (2025). [“Entendiendo el rol de la infraestructura de transmisión eléctrica para la transición energética: modelos, principales desafíos y casos.”](https://editorial.tirant.com/mex/libro/energia-2050-volumen-ii-david-enriquez-9788410713611) *In Energía 2050 Vol. II*, David Enríquez and Yolanda Villegas (eds.), Editorial Tirant Lo Blanch.

<!-- -->

1.  Gutiérrez-Meave, R., Hancevic, P., Núñez, H., Rosellón, J. (2024). [“Los efectos económicos de un proceso acelerado de electrificación y descarbonización en México.”](https://repositorio-digital.cide.edu/handle/11651/5906) *In La economía mexicana: un balance desde la academia*, Centro de Investigación y Docencia Económicas (CIDE), División de Economía.

#### Other Publications

2.  Gutiérrez-Meave, R. (2024). [“A book review of Tom Entwistle’s Public Management: A Research Overview.”](https://onlinelibrary.wiley.com/doi/10.1111/padm.13023) *Public Administration*.

<!-- -->

1.  Gutiérrez-Meave, R. (2022). [“Framing and Decisions: The Punctuations of the Mexican Power Generation Policy Subsystem.”](https://www.ceeol.com/search/book-detail?id=1175564#page=276) *European Administrative Area: Integration and Resilience Dynamics, EU-PAIR 2022*.

#### Funded Research

1.  Gutiérrez-Meave, R., Núñez, H., Rosellón, J. (2024). [“The Economic Effects of an Accelerated Electrification and Decarbonization Process in Latin America.”](https://scioteca.caf.com/handle/123456789/2252) Funded by CAF – Development Bank of Latin America. Research report.

#### Manuscripts Under Review

<!-- -->

5.  Gutierrez-Meave, R., Siciliano, M., Carr, J., ”Stuck Together or Better Together? Rethinking Stability and Flexibility in Intergovernmental Collaboration Networks.” Invited to Revise and Resubmit.

<!-- -->

4.  Massa, R., Gutierrez-Meave, R., Fondevila, G., Bonilla, G. “When Political Boundaries Become Liabilities: Metropolitan Fragmentation and Crime Convergence in the Mexico City Metropolitan Area.” *Under review.*

<!-- -->

3.  Gutierrez-Meave, R., ”Why Reinvent the Wheel? Institutional Design Replication in Interlocal Collaboration.”

<!-- -->

2.  Zhang, S., Gutierrez-Meave, R., Li, J., Carr, J. ”Selection-Based Accountability, Tie Strength, and Contract Design in Interlocal Service Agreements.” 

<!-- -->

1. Gutierrez-Meave, R., Krause, R., M., Siciliano, M., Deslatte, A., E-Zhera, M., ”Beyond Single Instruments: Organizational Capabilities and Regional Collaboration in Local EV Policy Portfolios.”

#### Works in Progress

5.  Gutierrez-Meave, R., "Who Do You Learn From? Relational Experience and Network
Exposure in the Replication of Interlocal Agreement Designs.”

<!-- -->

4.  Gutierrez-Meave, R., "Borrowing from Neighbors? Spatial Patterns in the Replication of
Interlocal Collaboration Agreements.”

<!-- -->

3.  Ghasemizade, M., Gutierrez-Meave, R., Gramling, C., Chawla, A., Albrecht, K., &
Lovato, J. "Making Local Government Contracts Legible: A Computational Pipeline for
Classifying and Mapping Intergovernmental Service Agreements.”

<!-- -->

2.  Sanchez, J., Gutierrez-Meave, R., Gaytan-Neri, E., ”Local governments and shared
services: Insights on institutional mechanisms, partners, and purpose.”

<!-- -->

1.  Gutierrez-Meave, R., Carr, J. Siciliano, M. "Beyond Relational Inertia: Exploration and Exploitation in Intergovernmental Contract Networks.”



